import type { Profession, ProfessionId, Scene } from './types'

export const professions: Profession[] = [
  {
    id: 'blacksmith',
    name: 'Кузнец',
    epithet: 'тот, кто знает цену железу',
    description: 'Умеет оценивать оружие, чинить снаряжение и замечать следы чужой работы.',
    bonus: '+2 здоровья, особые решения при работе с металлом.',
    startingItem: 'Кузнечный молоток',
    stats: { health: 2 },
  },
  {
    id: 'herbalist',
    name: 'Травник',
    epithet: 'тот, кто различает лекарство и яд',
    description: 'Распознаёт растения, болезни и следы отравления.',
    bonus: '+2 проницательности, особые решения с травами и недугами.',
    startingItem: 'Кожаная сумка с травами',
    stats: { insight: 2 },
  },
  {
    id: 'hunter',
    name: 'Охотник',
    epithet: 'тот, кто читает землю',
    description: 'Лучше видит следы, избегает засад и бережнее расходует силы в дороге.',
    bonus: '+2 выносливости, особые решения при выслеживании.',
    startingItem: 'Короткий охотничий лук',
    stats: { stamina: 2 },
  },
  {
    id: 'scribe',
    name: 'Писарь',
    epithet: 'тот, кто помнит чужие долги',
    description: 'Читает документы, распознаёт ложь в договорах и знает устройство княжеской власти.',
    bonus: '+1 проницательности и 5 монет.',
    startingItem: 'Письменный набор',
    stats: { insight: 1, coins: 5 },
  },
  {
    id: 'carter',
    name: 'Возчик',
    epithet: 'тот, кто знает каждую дорогу',
    description: 'Разбирается в торговле, грузах, дорогах и людях у застав.',
    bonus: '+1 выносливости и 5 монет.',
    startingItem: 'Крепкая дорожная верёвка',
    stats: { stamina: 1, coins: 5 },
  },
  {
    id: 'wanderer',
    name: 'Странник',
    epithet: 'тот, кому нечего терять',
    description: 'Не имеет ремесленной специализации, зато начинает путь с редкой свободой выбора.',
    bonus: '+1 ко всем основным качествам.',
    startingItem: 'Потёртый дорожный плащ',
    stats: { health: 1, stamina: 1, insight: 1 },
  },
]

export const professionById = Object.fromEntries(
  professions.map((profession) => [profession.id, profession]),
) as Record<ProfessionId, Profession>

export const scenes: Record<string, Scene> = {
  crossroads: {
    id: 'crossroads',
    region: 'Северный рубеж',
    title: 'Пепел на дороге',
    text: 'К вечеру ты доходишь до развилки. На столбе висит княжеская печать, сорванная вместе с куском кожи. В грязи лежит перевёрнутая телега, а из леса доносится короткий металлический звон. Дорога к селу пуста, хотя из труб поднимается дым.',
    choices: [
      {
        id: 'inspect-cart',
        label: 'Осмотреть телегу',
        consequence: 'Под холстом ты находишь следы поспешного обыска и одну уцелевшую монету.',
        nextSceneId: 'cart',
        effects: { stamina: -1, coins: 1 },
      },
      {
        id: 'follow-sound',
        label: 'Идти на металлический звон',
        consequence: 'Ты сходишь с дороги и замечаешь зарубки на деревьях. Кто-то хотел, чтобы его нашли.',
        nextSceneId: 'forest-bell',
        effects: { stamina: -2, insight: 1 },
      },
      {
        id: 'enter-village',
        label: 'Не задерживаться и идти в село',
        consequence: 'Ты добираешься до ворот до полной темноты, но стража встречает тебя с оружием.',
        nextSceneId: 'village-gate',
        effects: { stamina: -1 },
      },
    ],
  },
  cart: {
    id: 'cart',
    region: 'Северный рубеж',
    title: 'Чужой груз',
    text: 'Колёса целы, оглобли перерублены одним сильным ударом. Под телегой зажата рука, но тела нет. На доске вырезан знак местной гильдии перевозчиков. Из леса снова слышится звон, теперь ближе.',
    choices: [
      {
        id: 'repair-trace',
        label: 'Изучить срез на оглобле',
        consequence: 'По следу инструмента ты понимаешь: телегу остановили люди, а не зверь.',
        nextSceneId: 'forest-bell',
        effects: { insight: 2 },
        requiresProfession: 'blacksmith',
      },
      {
        id: 'take-rope',
        label: 'Забрать уцелевший ремень и идти к селу',
        consequence: 'Ремень ещё послужит. Ты уходишь прежде, чем хозяин звона покажется из леса.',
        nextSceneId: 'village-gate',
        item: 'Крепкий ремень',
      },
      {
        id: 'hide-wait',
        label: 'Спрятаться и дождаться того, кто идёт',
        consequence: 'Ожидание отнимает силы. Между деревьями появляется мальчик с маленьким колоколом.',
        nextSceneId: 'bell-boy',
        effects: { stamina: -2 },
      },
    ],
  },
  'forest-bell': {
    id: 'forest-bell',
    region: 'Чёрная опушка',
    title: 'Звон без храма',
    text: 'На ветке висит медный колокольчик. Под ним на коленях сидит мальчик лет десяти. Он не плачет и не смотрит на тебя. Вокруг нет ни единого следа, кроме твоих собственных.',
    choices: [
      {
        id: 'read-tracks',
        label: 'Осмотреть землю вокруг мальчика',
        consequence: 'Ты замечаешь примятую траву: следы есть, но их тщательно замели еловой веткой.',
        nextSceneId: 'bell-boy',
        effects: { insight: 1 },
        requiresProfession: 'hunter',
      },
      {
        id: 'speak-boy',
        label: 'Спросить, кто привёл его сюда',
        consequence: 'Мальчик отвечает чужим взрослым голосом: «Тот, кому село должно».',
        nextSceneId: 'bell-boy',
        effects: { insight: 1 },
      },
      {
        id: 'retreat',
        label: 'Отступить к селу',
        consequence: 'Ты не поворачиваешься спиной, пока звон не стихает. У ворот уже знают, что ты был в лесу.',
        nextSceneId: 'village-gate',
        effects: { stamina: -1 },
      },
    ],
  },
  'bell-boy': {
    id: 'bell-boy',
    region: 'Чёрная опушка',
    title: 'Долг села',
    text: 'На шее мальчика виден тонкий след от верёвки. Он жив, но холоден как вода из колодца. В кармане у него сухая веточка с тремя белыми ягодами. Из-за деревьев доносится тяжёлое дыхание.',
    choices: [
      {
        id: 'identify-berries',
        label: 'Рассмотреть белые ягоды',
        consequence: 'Это не яд, а редкое средство, замедляющее сердце. Мальчика намеренно ввели в подобие смерти.',
        nextSceneId: 'village-gate',
        effects: { insight: 2 },
        item: 'Белые ягоды',
        requiresProfession: 'herbalist',
      },
      {
        id: 'carry-boy',
        label: 'Поднять мальчика и нести в село',
        consequence: 'Он почти ничего не весит. Когда ты отходишь, колокол начинает звонить сам.',
        nextSceneId: 'village-gate',
        effects: { stamina: -3, health: -1 },
        item: 'Медный колокольчик',
      },
      {
        id: 'leave-mark',
        label: 'Оставить знак и вернуться с людьми',
        consequence: 'Ты запоминаешь место, но когда достигаешь ворот, лес за спиной уже выглядит иначе.',
        nextSceneId: 'village-gate',
        effects: { insight: 1 },
      },
    ],
  },
  'village-gate': {
    id: 'village-gate',
    region: 'Село Вересково',
    title: 'Закрытые ворота',
    text: 'За частоколом горят факелы. Старший стражник требует назвать ремесло и цель прихода. У его людей мокрые сапоги, хотя дождя не было три дня. На башне висит такой же колокол, как в лесу.',
    choices: [
      {
        id: 'state-trade',
        label: 'Назвать своё ремесло и попросить ночлег',
        consequence: 'После долгой паузы ворота открываются. Тебя пропускают, но записывают имя в чёрную книгу.',
        nextSceneId: 'tavern',
        effects: { coins: -1 },
      },
      {
        id: 'study-record',
        label: 'Потребовать показать приказ о закрытии ворот',
        consequence: 'Печать настоящая, но дата исправлена. Стражник понимает, что ты это заметил, и становится сговорчивее.',
        nextSceneId: 'tavern',
        effects: { insight: 2 },
        requiresProfession: 'scribe',
      },
      {
        id: 'offer-delivery',
        label: 'Предложить сведения о разбитой телеге',
        consequence: 'Начальник стражи впускает тебя бесплатно и просит молчать о знаке перевозчиков.',
        nextSceneId: 'tavern',
        effects: { coins: 2 },
        requiresProfession: 'carter',
      },
    ],
  },
  tavern: {
    id: 'tavern',
    region: 'Село Вересково',
    title: 'Первая ночь',
    text: 'Внутри трактира слишком тихо. На доске заказов висят три листа: пропавший сборщик податей, больной колодец и награда за голову лесного зверя. Хозяин ставит перед тобой воду и говорит: «Выбирай работу до рассвета. После рассвета выбирать будут уже за тебя».',
    choices: [
      {
        id: 'taxman-contract',
        label: 'Взять заказ о сборщике податей',
        consequence: 'Ты принимаешь первый настоящий контракт. На этом пролог заканчивается.',
        nextSceneId: 'crossroads',
        effects: { coins: 5, insight: 1 },
      },
      {
        id: 'well-contract',
        label: 'Взять заказ о больном колодце',
        consequence: 'Ты принимаешь первый настоящий контракт. На этом пролог заканчивается.',
        nextSceneId: 'crossroads',
        effects: { coins: 4, health: 1 },
      },
      {
        id: 'beast-contract',
        label: 'Взять заказ на лесного зверя',
        consequence: 'Ты принимаешь первый настоящий контракт. На этом пролог заканчивается.',
        nextSceneId: 'crossroads',
        effects: { coins: 6, stamina: 1 },
      },
    ],
  },
}
