export const marshQuests = [
  {
    id: 'sunken-bell',
    title: 'Глухой колокол',
    summary: 'Из затопленной часовни каждую ночь доносится звон, после которого исчезают лодочники.',
  },
  {
    id: 'white-fever',
    title: 'Белая лихорадка',
    summary: 'Рабочие соляных варниц покрываются белыми пятнами и начинают говорить голосами утонувших.',
  },
  {
    id: 'reed-oath',
    title: 'Клятва тростника',
    summary: 'Тростниковые охотники требуют вернуть им старую гать и угрожают перекрыть путь через топи.',
  },
]

export const marshQuestIds = new Set(marshQuests.map((quest) => quest.id))

export const marshScenes = {
  'marsh-threshold': {
    id: 'marsh-threshold',
    region: 'Соляные топи',
    title: 'Белая вода',
    text: 'За последней сухой сосной дорога превращается в узкую гать. Вода по обе стороны белая от соли, а на дальнем островке стоит дом с тремя трубами и ни одной закрытой дверью.',
    choices: [
      {
        id: 'marsh-enter',
        label: 'Идти к дому солеваров',
        consequence: 'Доски под ногами стонут, но держат. В доме тебя встречают так, будто ждали именно сегодня.',
        nextSceneId: 'salt-house',
        startChapter: true,
        effects: { stamina: -1 },
      },
      {
        id: 'marsh-study-water',
        label: 'Осмотреть белую воду и следы у гати',
        consequence: 'На соляной корке видны отпечатки босых ног, ведущие от воды к человеческому жилью.',
        nextSceneId: 'salt-house',
        startChapter: true,
        addFlag: 'barefoot-tracks',
        effects: { insight: 1, stamina: -1 },
        requires: { profession: 'hunter' },
      },
      {
        id: 'marsh-read-post',
        label: 'Разобрать вырезанную на столбе надпись',
        consequence: 'Надпись старше нынешних князей: «Колокол принадлежит тем, кого он позовёт последними».',
        nextSceneId: 'salt-house',
        startChapter: true,
        addFlag: 'old-bell-law',
        effects: { insight: 2 },
        requires: { profession: 'scribe' },
      },
    ],
  },
  'salt-house': {
    id: 'salt-house',
    region: 'Дом солеваров',
    title: 'Три долга топей',
    text: 'Старшая солеварка Ведана кладёт на стол три предмета: зелёный язык колокола, белую повязку и связку чёрного тростника. За каждым стоит чужая смерть и спор, который никто не хочет решать первым.',
    choices: [
      {
        id: 'take-bell-contract',
        label: 'Разобраться со звонницей',
        consequence: 'Ведана отдаёт тебе лодочный крюк и показывает затопленную часовню.',
        nextSceneId: 'bell-causeway',
        startQuest: 'sunken-bell',
        requires: { questAvailable: 'sunken-bell' },
      },
      {
        id: 'take-fever-contract',
        label: 'Осмотреть больных солеваров',
        consequence: 'Тебя проводят к варницам, где соль кипит даже в холодной воде.',
        nextSceneId: 'salt-pans',
        startQuest: 'white-fever',
        requires: { questAvailable: 'white-fever' },
      },
      {
        id: 'take-reed-contract',
        label: 'Встретиться с тростниковыми охотниками',
        consequence: 'Проводник отмечает путь узлами на верёвке и отказывается идти дальше первого острова.',
        nextSceneId: 'reed-maze',
        startQuest: 'reed-oath',
        requires: { questAvailable: 'reed-oath' },
      },
      {
        id: 'marsh-rest',
        label: 'Заплатить 3 монеты за сухой угол и горячую воду',
        consequence: 'Соль вытягивает сырость из одежды, а сон возвращает часть сил.',
        nextSceneId: 'salt-house',
        effects: { coins: -3, fullRest: true },
        requires: { minCoins: 3 },
      },
      {
        id: 'marsh-council',
        label: 'Созвать совет после трёх расследований',
        consequence: 'В доме собираются солевары, лодочники и люди тростника. Все требуют одного решения, но называют долг по-разному.',
        nextSceneId: 'marsh-council',
        requires: { allQuests: true },
      },
    ],
  },
  'bell-causeway': {
    id: 'bell-causeway',
    region: 'Затопленная гать',
    title: 'След под водой',
    text: 'К часовне ведёт цепочка столбов. Между ними натянута медная проволока, а под водой лежат свежие следы волочения.',
    choices: [
      {
        id: 'bell-cut-wire',
        label: 'Снять натяжение и обезвредить проволоку',
        consequence: 'Проволока больше не передаёт звон на берег. В воде что-то перестаёт двигаться вслед за тобой.',
        nextSceneId: 'sunken-chapel-story',
        addFlag: 'bell-silenced',
        requires: { profession: 'blacksmith' },
      },
      {
        id: 'bell-use-hook',
        label: 'Подтянуть затонувшую цепь дорожным крюком',
        consequence: 'Цепь выводит к боковому входу. Там можно подойти к колоколу, не пересекая открытый неф.',
        nextSceneId: 'sunken-chapel-story',
        addFlag: 'chapel-flank',
        requires: { profession: 'carter' },
      },
      {
        id: 'bell-wade',
        label: 'Идти по столбам прямо к часовне',
        consequence: 'Рассол обжигает кожу через сапоги. Ты добираешься до двери, оставляя в воде тонкую кровавую полосу.',
        nextSceneId: 'sunken-chapel-story',
        injury: { kind: 'salt-burn', title: 'Соляной ожог', severity: 1, source: 'Переход к затопленной часовне' },
        effects: { health: -1, stamina: -2 },
      },
    ],
  },
  'sunken-chapel-story': {
    id: 'sunken-chapel-story',
    region: 'Затопленная часовня',
    title: 'Тот, кто держит язык',
    text: 'Колокол висит под водой, но звон идёт сверху. На балке сидит утопленник и держит зелёный язык колокола обеими руками. За его спиной вырезаны имена лодочников.',
    choices: [
      {
        id: 'bell-law',
        label: 'Произнести старый закон колокола',
        consequence: 'Утопленник узнаёт слова. Он отдаёт язык, но требует не возвращать его тем, кто вычеркнул погибших из книг.',
        nextSceneId: 'bell-verdict',
        addFlag: 'bell-willing',
        requires: { flag: 'old-bell-law' },
      },
      {
        id: 'bell-fight',
        label: 'Отнять язык колокола силой',
        consequence: 'Утопленник срывается с балки, и вода в часовне поднимается до пояса.',
        nextSceneId: 'sunken-chapel-story',
        encounter: {
          enemyId: 'bell-drowner',
          enemyName: 'Колокольный утопленник',
          enemyStyle: 'ranged',
          enemyHealth: 22,
          difficulty: 4,
          terrainId: 'sunken-chapel',
          terrainName: 'Затопленная часовня',
          initialDistance: 2,
          maxDistance: 2,
          movementCost: 1,
          trophyId: 'drowned-brass',
          trophyName: 'Утопленная бронза',
          questId: 'sunken-bell',
          victorySceneId: 'bell-verdict',
          fleeSceneId: 'salt-house',
        },
      },
    ],
  },
  'bell-verdict': {
    id: 'bell-verdict',
    region: 'Берег звонницы',
    title: 'Кому должен звонить колокол',
    text: 'Зелёный язык колокола у тебя. Солевары хотят вернуть его на башню, а лодочники просят утопить навсегда, чтобы звон больше никого не звал.',
    choices: [
      {
        id: 'bell-return',
        label: 'Вернуть язык и записать имена погибших',
        consequence: 'Колокол снова звонит, но теперь каждый удар начинается с чтения имён. Солевары платят полностью.',
        nextSceneId: 'salt-house',
        effects: { coins: 15, reputation: 3, experience: 16 },
        completeQuest: { id: 'sunken-bell', outcome: 'restore-with-names' },
      },
      {
        id: 'bell-drown',
        label: 'Утопить язык в глубокой яме',
        consequence: 'Звон прекращается. Лодочники благодарят тебя, а дом солеваров запирает одну из дверей.',
        nextSceneId: 'salt-house',
        effects: { coins: 10, reputation: 1, experience: 18 },
        addFlag: 'bell-buried',
        completeQuest: { id: 'sunken-bell', outcome: 'silence-bell' },
      },
    ],
  },
  'salt-pans': {
    id: 'salt-pans',
    region: 'Белые варницы',
    title: 'Соль на коже',
    text: 'Больные лежат между чанами. Белые пятна идут от пальцев к сердцу, а из подвального люка тянет сладким болотным запахом.',
    choices: [
      {
        id: 'fever-herbs',
        label: 'Сравнить пятна с действием горьких трав',
        consequence: 'Это не болезнь, а медленное отравление спорами, которые соль вытягивает из старых досок.',
        nextSceneId: 'brine-cellar',
        addFlag: 'fever-spores',
        effects: { insight: 2 },
        requires: { profession: 'herbalist' },
      },
      {
        id: 'fever-ledger',
        label: 'Проверить смены больных по книге варниц',
        consequence: 'Заболевают только те, кто работает у третьего чана. Его поставили над закрытым колодцем.',
        nextSceneId: 'brine-cellar',
        addFlag: 'third-vat',
        effects: { insight: 2 },
        requires: { profession: 'scribe' },
      },
      {
        id: 'fever-open-cellar',
        label: 'Открыть подвал и спуститься',
        consequence: 'На лестнице осыпается белая плесень. К вечеру тебя начинает знобить.',
        nextSceneId: 'brine-cellar',
        injury: { kind: 'marsh-fever', title: 'Болотная лихорадка', severity: 1, source: 'Споры под соляными варницами' },
        effects: { stamina: -2 },
      },
    ],
  },
  'brine-cellar': {
    id: 'brine-cellar',
    region: 'Подвал варниц',
    title: 'Колодец под чаном',
    text: 'Под третьим чаном скрыт старый колодец. В нём лежат мешки с костями и княжескими пломбами. Споры растут на ткани, которой когда-то закрывали лица умерших.',
    choices: [
      {
        id: 'fever-burn',
        label: 'Сжечь мешки и остановить варницу',
        consequence: 'Третий чан остывает. Рабочие спасены, но дом теряет половину дохода и обвиняет тебя в разорении.',
        nextSceneId: 'salt-house',
        effects: { coins: 9, reputation: 4, experience: 18 },
        addFlag: 'pans-closed',
        completeQuest: { id: 'white-fever', outcome: 'close-vat' },
      },
      {
        id: 'fever-filter',
        label: 'Сделать фильтр из ткани, угля и соли',
        consequence: 'Фильтр задерживает споры, но кости остаются под работающим чаном. Люди выздоравливают, а тайна продолжает приносить прибыль.',
        nextSceneId: 'salt-house',
        effects: { coins: 14, reputation: 1, experience: 14 },
        addFlag: 'bones-hidden',
        completeQuest: { id: 'white-fever', outcome: 'filter-and-hide' },
        requires: { item: 'charcoal' },
      },
    ],
  },
  'reed-maze': {
    id: 'reed-maze',
    region: 'Чёрный тростник',
    title: 'Путь, который меняется',
    text: 'Тростник выше человеческого роста. Узлы на верёвке показывают путь, но каждый поворот возвращает тебя к одному и тому же мёртвому дереву.',
    choices: [
      {
        id: 'reed-follow-tracks',
        label: 'Искать срезанные стебли и следы лодок',
        consequence: 'Охотники специально ведут тебя кругами. Настоящий путь скрыт под плавающими циновками.',
        nextSceneId: 'reed-camp',
        addFlag: 'reed-path',
        effects: { insight: 2 },
        requires: { profession: 'hunter' },
      },
      {
        id: 'reed-use-cordage',
        label: 'Закрепить путь болотной верёвкой',
        consequence: 'Верёвка не даёт тростнику вернуть тебя назад. Ты выходишь прямо к лагерю охотников.',
        nextSceneId: 'reed-camp',
        removeItem: 'marsh-cordage',
        addFlag: 'marked-path',
        requires: { item: 'marsh-cordage' },
      },
      {
        id: 'reed-force-way',
        label: 'Прорубить проход напрямую',
        consequence: 'Стебли режут руки и лицо. Зато охотники больше не могут сделать вид, что не заметили тебя.',
        nextSceneId: 'reed-camp',
        injury: { kind: 'deep-cut', title: 'Глубокий порез', severity: 2, source: 'Чёрный тростник' },
        effects: { health: -2, stamina: -2 },
      },
    ],
  },
  'reed-camp': {
    id: 'reed-camp',
    region: 'Лагерь тростниковых охотников',
    title: 'Клятва старой гати',
    text: 'Предводительница охотников показывает княжеский договор: гать принадлежала их семьям, пока солевары не перенесли межевые столбы ночью. За палатками готовят ловушки для обозов.',
    choices: [
      {
        id: 'reed-show-tracks',
        label: 'Признать право охотников и потребовать открыть путь',
        consequence: 'Охотники соглашаются пропускать одиночных путников, но соляные обозы останутся их добычей.',
        nextSceneId: 'reed-verdict',
        addFlag: 'reed-rights',
        requires: { flag: 'barefoot-tracks' },
      },
      {
        id: 'reed-disarm',
        label: 'Обезвредить ловушки и вынудить их говорить',
        consequence: 'Одна ловушка щёлкает слишком близко. Из тростника выходит ловчий в маске из коры.',
        nextSceneId: 'reed-camp',
        encounter: {
          enemyId: 'reed-stalker',
          enemyName: 'Тростниковый ловчий',
          enemyStyle: 'skirmisher',
          enemyHealth: 18,
          difficulty: 3,
          terrainId: 'reed-maze',
          terrainName: 'Тростниковый лабиринт',
          initialDistance: 2,
          maxDistance: 3,
          movementCost: 2,
          trophyId: 'black-reed',
          trophyName: 'Чёрный тростник',
          questId: 'reed-oath',
          victorySceneId: 'reed-verdict',
          fleeSceneId: 'salt-house',
        },
      },
      {
        id: 'reed-snare-peace',
        label: 'Показать собственную тростниковую ловушку',
        consequence: 'Охотники признают, что ты понимаешь цену их ремесла. Разговор начинается без оружия.',
        nextSceneId: 'reed-verdict',
        addFlag: 'hunter-respect',
        removeItem: 'reed-snare',
        requires: { item: 'reed-snare' },
      },
    ],
  },
  'reed-verdict': {
    id: 'reed-verdict',
    region: 'Старая гать',
    title: 'Две дороги на одном месте',
    text: 'Солевары требуют свободного проезда, охотники требуют вернуть землю. Полностью удовлетворить обе стороны нельзя.',
    choices: [
      {
        id: 'reed-shared-road',
        label: 'Разделить гать по дням и поставить общие метки',
        consequence: 'По чётным дням идут обозы, по нечётным охотники закрывают путь. Мир держится на расписании, а не доверии.',
        nextSceneId: 'salt-house',
        effects: { coins: 12, reputation: 3, experience: 16 },
        completeQuest: { id: 'reed-oath', outcome: 'shared-road' },
      },
      {
        id: 'reed-return-land',
        label: 'Вернуть гать охотникам',
        consequence: 'Обозы теперь платят пошлину тростниковым семьям. Дом солеваров теряет власть над дорогой.',
        nextSceneId: 'salt-house',
        effects: { coins: 8, reputation: 4, experience: 18 },
        addFlag: 'reed-owns-gate',
        completeQuest: { id: 'reed-oath', outcome: 'return-land' },
      },
    ],
  },
  'marsh-council': {
    id: 'marsh-council',
    region: 'Дом солеваров',
    title: 'Кому принадлежат топи',
    text: 'Перед тобой лежат три доказательства: имена утонувших, кости под варницей и старый договор на гать. Любой порядок сохранит жизнь одним и отнимет доход у других.',
    choices: [
      {
        id: 'ending-salt-house',
        label: 'Поддержать дом солеваров и потребовать письменных уступок',
        consequence: 'Дом сохраняет варницы и дорогу, но обязуется записать погибших и платить охотникам. Порядок выжил, потому что стал дороже.',
        nextSceneId: 'marsh-end',
        chapterComplete: true,
        ending: 'salt-house-reformed',
        effects: { coins: 24, reputation: 2, experience: 30 },
        addItem: { id: 'salt-oath-token', name: 'Жетон соляной клятвы' },
      },
      {
        id: 'ending-free-marsh',
        label: 'Лишить дом исключительного права на соль и гать',
        consequence: 'Топи становятся беднее, свободнее и опаснее. Ни одна семья больше не владеет всеми дорогами сразу.',
        nextSceneId: 'marsh-end',
        chapterComplete: true,
        ending: 'free-marsh',
        effects: { coins: 14, reputation: 6, experience: 34 },
        addItem: { id: 'reed-oath-token', name: 'Знак свободной гати' },
      },
      {
        id: 'ending-burn-ledgers',
        label: 'Сжечь договоры и скрыть доказательства',
        consequence: 'Старые долги исчезают вместе с бумагой, но каждый участник совета рассказывает свою версию. Топи получают мир без общей правды.',
        nextSceneId: 'marsh-end',
        chapterComplete: true,
        ending: 'ash-truce',
        effects: { coins: 20, reputation: 0, experience: 32 },
        addItem: { id: 'blank-brass-token', name: 'Безымянный бронзовый жетон' },
      },
    ],
  },
  'marsh-end': {
    id: 'marsh-end',
    region: 'Край Соляных топей',
    title: 'Вторая зола',
    text: 'Соляные топи не стали безопасными. Они лишь запомнили, чьё слово оказалось тяжелее воды. Дальше дорога ведёт туда, где князья уже знают имя твоего рода.',
    choices: [
      {
        id: 'marsh-return-house',
        label: 'Вернуться к сухому огню и продолжить путь',
        consequence: 'Ты возвращаешься к дому солеваров. Свободные контракты остаются доступны.',
        nextSceneId: 'salt-house',
      },
    ],
  },
}

export const marshSceneIds = new Set(Object.keys(marshScenes))
