export const storyQuests = [
  {
    id: 'taxman',
    title: 'Пропавший сборщик',
    summary: 'Княжеский сборщик исчез на северной дороге вместе с сундуком и охраной.',
  },
  {
    id: 'well',
    title: 'Больной колодец',
    summary: 'Вода пахнет болотом, а заболевшие слышат голос из глубины.',
  },
  {
    id: 'beast',
    title: 'Зверь из пепла',
    summary: 'Нечто режет скот и оставляет горячие следы на холодной земле.',
  },
]

export const storyQuestIds = new Set(storyQuests.map((quest) => quest.id))

export const storyScenes = {
  crossroads: {
    id: 'crossroads',
    region: 'Северный рубеж',
    title: 'Пепел на дороге',
    text: 'К вечеру ты доходишь до развилки. На столбе висит княжеская печать, сорванная вместе с куском кожи. В грязи лежит перевёрнутая телега, а из леса доносится короткий металлический звон.',
    choices: [
      {
        id: 'inspect-cart',
        label: 'Осмотреть телегу',
        consequence: 'Под холстом ты находишь следы поспешного обыска и одну уцелевшую монету.',
        nextSceneId: 'cart',
        effects: { stamina: -1, coins: 1 },
      },
      {
        id: 'follow-sound',
        label: 'Идти на металлический звон',
        consequence: 'Ты сходишь с дороги и замечаешь зарубки на деревьях. Кто-то хотел, чтобы его нашли.',
        nextSceneId: 'forest-bell',
        effects: { stamina: -2, insight: 1 },
      },
      {
        id: 'enter-village',
        label: 'Не задерживаться и идти в село',
        consequence: 'Ты добираешься до ворот до полной темноты, но стража встречает тебя с оружием.',
        nextSceneId: 'village-gate',
        effects: { stamina: -1 },
      },
    ],
  },
  cart: {
    id: 'cart',
    region: 'Северный рубеж',
    title: 'Чужой груз',
    text: 'Колёса целы, оглобли перерублены одним сильным ударом. Под телегой зажата рука, но тела нет. На доске вырезан знак местной гильдии перевозчиков.',
    choices: [
      {
        id: 'repair-trace',
        label: 'Изучить срез на оглобле',
        consequence: 'По следу инструмента ты понимаешь: телегу остановили люди, а не зверь.',
        nextSceneId: 'forest-bell',
        effects: { insight: 2 },
        requires: { profession: 'blacksmith' },
      },
      {
        id: 'take-rope',
        label: 'Забрать уцелевший ремень и идти к селу',
        consequence: 'Ремень ещё послужит. Ты уходишь прежде, чем хозяин звона покажется из леса.',
        nextSceneId: 'village-gate',
        addItem: { id: 'strong-strap', name: 'Крепкий ремень' },
      },
      {
        id: 'hide-wait',
        label: 'Спрятаться и дождаться того, кто идёт',
        consequence: 'Ожидание отнимает силы. Между деревьями появляется мальчик с маленьким колоколом.',
        nextSceneId: 'bell-boy',
        effects: { stamina: -2 },
      },
    ],
  },
  'forest-bell': {
    id: 'forest-bell',
    region: 'Чёрная опушка',
    title: 'Звон без храма',
    text: 'На ветке висит медный колокольчик. Под ним на коленях сидит мальчик лет десяти. Он не плачет и не смотрит на тебя. Вокруг нет ни единого следа, кроме твоих собственных.',
    choices: [
      {
        id: 'read-tracks',
        label: 'Осмотреть землю вокруг мальчика',
        consequence: 'Ты замечаешь примятую траву: следы есть, но их тщательно замели еловой веткой.',
        nextSceneId: 'bell-boy',
        effects: { insight: 1 },
        requires: { profession: 'hunter' },
      },
      {
        id: 'speak-boy',
        label: 'Спросить, кто привёл его сюда',
        consequence: 'Мальчик отвечает чужим взрослым голосом: «Тот, кому село должно».',
        nextSceneId: 'bell-boy',
        effects: { insight: 1 },
      },
      {
        id: 'retreat',
        label: 'Отступить к селу',
        consequence: 'Ты не поворачиваешься спиной, пока звон не стихает. У ворот уже знают, что ты был в лесу.',
        nextSceneId: 'village-gate',
        effects: { stamina: -1 },
      },
    ],
  },
  'bell-boy': {
    id: 'bell-boy',
    region: 'Чёрная опушка',
    title: 'Долг села',
    text: 'На шее мальчика виден тонкий след от верёвки. Он жив, но холоден как вода из колодца. В кармане у него сухая веточка с тремя белыми ягодами.',
    choices: [
      {
        id: 'identify-berries',
        label: 'Рассмотреть белые ягоды',
        consequence: 'Это не яд, а редкое средство, замедляющее сердце. Мальчика намеренно ввели в подобие смерти.',
        nextSceneId: 'village-gate',
        effects: { insight: 2 },
        addItem: { id: 'white-berries', name: 'Белые ягоды' },
        requires: { profession: 'herbalist' },
      },
      {
        id: 'carry-boy',
        label: 'Поднять мальчика и нести в село',
        consequence: 'Он почти ничего не весит. Когда ты отходишь, колокол начинает звонить сам.',
        nextSceneId: 'village-gate',
        effects: { stamina: -3, health: -1 },
        addItem: { id: 'copper-bell', name: 'Медный колокольчик' },
      },
      {
        id: 'leave-mark',
        label: 'Оставить знак и вернуться с людьми',
        consequence: 'Ты запоминаешь место, но когда достигаешь ворот, лес за спиной уже выглядит иначе.',
        nextSceneId: 'village-gate',
        effects: { insight: 1 },
      },
    ],
  },
  'village-gate': {
    id: 'village-gate',
    region: 'Село Вересково',
    title: 'Закрытые ворота',
    text: 'За частоколом горят факелы. Старший стражник требует назвать ремесло и цель прихода. У его людей мокрые сапоги, хотя дождя не было три дня.',
    choices: [
      {
        id: 'state-trade',
        label: 'Назвать своё ремесло и попросить ночлег',
        consequence: 'После долгой паузы ворота открываются. Тебя записывают в чёрную книгу.',
        nextSceneId: 'tavern',
        effects: { coins: -1 },
        requires: { minCoins: 1 },
      },
      {
        id: 'study-record',
        label: 'Потребовать приказ о закрытии ворот',
        consequence: 'Печать настоящая, но дата исправлена. Стражник понимает, что ты это заметил.',
        nextSceneId: 'tavern',
        effects: { insight: 2 },
        requires: { profession: 'scribe' },
      },
      {
        id: 'offer-delivery',
        label: 'Предложить сведения о разбитой телеге',
        consequence: 'Начальник стражи впускает тебя бесплатно и просит молчать о знаке перевозчиков.',
        nextSceneId: 'tavern',
        effects: { coins: 2 },
        requires: { profession: 'carter' },
      },
    ],
  },
  tavern: {
    id: 'tavern',
    region: 'Село Вересково',
    title: 'Доска заказов',
    text: 'Трактир остаётся единственным местом, где чужаку дают работу раньше, чем задают вопросы. На доске висят три заказа. Каждый обещает плату, и каждый написан рукой человека, который рассказал не всё.',
    choices: [
      {
        id: 'taxman-contract',
        label: 'Взять заказ о сборщике податей',
        consequence: 'Ты принимаешь заказ старосты и выходишь на северную дорогу.',
        nextSceneId: 'taxman-road',
        startQuest: 'taxman',
        requires: { questAvailable: 'taxman' },
      },
      {
        id: 'well-contract',
        label: 'Взять заказ о больном колодце',
        consequence: 'Ты обещаешь осмотреть колодец до следующего рассвета.',
        nextSceneId: 'well-square',
        startQuest: 'well',
        requires: { questAvailable: 'well' },
      },
      {
        id: 'beast-contract',
        label: 'Взять заказ на зверя из пепла',
        consequence: 'Охотники отдают тебе карту последних нападений.',
        nextSceneId: 'beast-edge',
        startQuest: 'beast',
        requires: { questAvailable: 'beast' },
      },
      {
        id: 'rest-at-tavern',
        label: 'Заплатить 2 монеты и отдохнуть',
        consequence: 'Несколько часов сна возвращают силы, но мир не ждёт.',
        nextSceneId: 'tavern',
        effects: { coins: -2, fullRest: true },
        requires: { minCoins: 2 },
      },
      {
        id: 'leave-vereskovo',
        label: 'Покинуть Вересково и завершить первую главу',
        consequence: 'Три истории села остаются позади. Теперь твоё имя знают и люди, и то, что живёт под их домами.',
        nextSceneId: 'chapter-end',
        requires: { allQuests: true },
        chapterComplete: true,
      },
    ],
  },
  'taxman-road': {
    id: 'taxman-road',
    region: 'Северная дорога',
    title: 'Застава без князя',
    text: 'У старой заставы висит новый герб. На снегу следы шести лошадей, но в журнале записано только три. Из сторожки доносится спор о том, кому принадлежит сундук сборщика.',
    choices: [
      {
        id: 'tax-ledger',
        label: 'Проверить журнал заставы',
        consequence: 'Записи подделаны одной рукой. Сборщик приехал сюда добровольно и встречался с дорожным десятником.',
        nextSceneId: 'taxman-camp',
        effects: { insight: 2 },
        addFlag: 'taxman-forgery',
        requires: { profession: 'scribe' },
      },
      {
        id: 'tax-tracks',
        label: 'Обойти заставу по следам лошадей',
        consequence: 'Следы приводят к укрытому оврагу. Ты подходишь к лагерю с неудобной для стражи стороны.',
        nextSceneId: 'taxman-camp',
        effects: { stamina: -1 },
        addFlag: 'taxman-ambush',
        requires: { profession: 'hunter' },
      },
      {
        id: 'tax-enter',
        label: 'Войти и потребовать ответа',
        consequence: 'Разговор заканчивается, когда десятник кладёт руку на меч.',
        nextSceneId: 'taxman-camp',
        effects: { stamina: -1 },
      },
    ],
  },
  'taxman-camp': {
    id: 'taxman-camp',
    region: 'Северная дорога',
    title: 'Цена закона',
    text: 'Сборщик жив и пьёт за одним столом с разбойниками. Десятник объясняет: князь берёт слишком много, поэтому они решили брать раньше него. В углу стоит сундук с деньгами трёх сёл.',
    choices: [
      {
        id: 'tax-expose',
        label: 'Показать, что подделка уже раскрыта',
        consequence: 'Люди десятника не готовы умирать за очевидную ложь. Они расходятся, оставив главаря одного.',
        nextSceneId: 'taxman-verdict',
        effects: { reputation: 1 },
        requires: { flag: 'taxman-forgery' },
      },
      {
        id: 'tax-attack',
        label: 'Потребовать вернуть сундук',
        consequence: 'Десятник встаёт, застёгивает кольчугу и обнажает меч.',
        nextSceneId: 'taxman-camp',
        encounter: {
          contractId: 'toll-robber',
          questId: 'taxman',
          victorySceneId: 'taxman-verdict',
          fleeSceneId: 'tavern',
        },
      },
      {
        id: 'tax-bribe',
        label: 'Согласиться на долю и уйти',
        consequence: 'Ты берёшь грязные деньги. Вересково запомнит не правду, а отсутствие возвращённого сундука.',
        nextSceneId: 'tavern',
        effects: { coins: 14, reputation: -2, experience: 5 },
        completeQuest: { id: 'taxman', outcome: 'bribe' },
      },
    ],
  },
  'taxman-verdict': {
    id: 'taxman-verdict',
    region: 'Северная дорога',
    title: 'Чужие подати',
    text: 'Сундук возвращён, но сборщик просит не вести его в село. Он утверждает, что староста первым предложил схему и теперь сделает его единственным виноватым.',
    choices: [
      {
        id: 'tax-deliver',
        label: 'Вернуть сборщика и сундук старосте',
        consequence: 'Ты исполняешь условия заказа. Закон торжествует ровно до тех пор, пока двери старосты не закрываются.',
        nextSceneId: 'tavern',
        effects: { coins: 10, reputation: 2, experience: 8 },
        completeQuest: { id: 'taxman', outcome: 'law' },
      },
      {
        id: 'tax-publish',
        label: 'Отдать деньги жителям и обнародовать записи',
        consequence: 'Село получает свои деньги, а староста — врагов. Платы почти нет, зато твоё имя начинают произносить вслух.',
        nextSceneId: 'tavern',
        effects: { coins: 3, reputation: 4, experience: 10 },
        completeQuest: { id: 'taxman', outcome: 'truth' },
      },
    ],
  },
  'well-square': {
    id: 'well-square',
    region: 'Село Вересково',
    title: 'Вода, которая слушает',
    text: 'Колодец обвязан красными нитями. Больные повторяют одну и ту же фразу: «Верните камень на дно». Староста запрещает спускаться, но ночью у колодца выставляют вооружённую стражу.',
    choices: [
      {
        id: 'well-samples',
        label: 'Исследовать воду и налёт на ведре',
        consequence: 'В воде есть болотная слизь и след старого усыпляющего настоя. Кто-то скрывает симптомы, а не лечит причину.',
        nextSceneId: 'well-mouth',
        effects: { insight: 2 },
        addFlag: 'well-antidote',
        requires: { profession: 'herbalist' },
      },
      {
        id: 'well-question',
        label: 'Расспросить семьи заболевших',
        consequence: 'Все заболевшие участвовали в расширении колодца. Неделю назад рабочие подняли со дна чёрный камень.',
        nextSceneId: 'well-mouth',
        effects: { insight: 1 },
      },
      {
        id: 'well-descend',
        label: 'Сразу спуститься по цепи',
        consequence: 'Камни скользкие, а снизу кто-то медленно натягивает цепь.',
        nextSceneId: 'well-mouth',
        effects: { stamina: -2 },
      },
    ],
  },
  'well-mouth': {
    id: 'well-mouth',
    region: 'Под Вересковом',
    title: 'Ниже воды',
    text: 'Под обычным колодцем скрыта старая каменная шахта. В нише лежит пустой постамент, а рядом шевелится утопленник, вросший пальцами в кладку.',
    choices: [
      {
        id: 'well-poison',
        label: 'Бросить в воду смесь, ослабляющую мёртвую плоть',
        consequence: 'Слизь на теле существа темнеет. Оно отрывается от стены и идёт на тебя медленнее.',
        nextSceneId: 'well-mouth',
        addFlag: 'well-weakened',
        encounter: {
          contractId: 'drowned-dead',
          questId: 'well',
          victorySceneId: 'well-verdict',
          fleeSceneId: 'tavern',
        },
        requires: { flag: 'well-antidote' },
      },
      {
        id: 'well-fight',
        label: 'Добраться до камня силой',
        consequence: 'Вода поднимается, а хозяин глубины заслоняет единственную лестницу.',
        nextSceneId: 'well-mouth',
        encounter: {
          contractId: 'drowned-dead',
          questId: 'well',
          victorySceneId: 'well-verdict',
          fleeSceneId: 'tavern',
        },
      },
    ],
  },
  'well-verdict': {
    id: 'well-verdict',
    region: 'Под Вересковом',
    title: 'Камень обещаний',
    text: 'Чёрный камень покрыт именами людей, которые когда-то построили село. Последняя строка свежая: нынешний староста обещал воде одну жизнь каждую зиму в обмен на полные колодцы.',
    choices: [
      {
        id: 'well-return-stone',
        label: 'Вернуть камень на постамент',
        consequence: 'Вода очищается, но договор остаётся действовать. Ты спас больных и оставил будущую цену другим.',
        nextSceneId: 'tavern',
        effects: { coins: 8, reputation: 1, experience: 10, health: 2 },
        completeQuest: { id: 'well', outcome: 'restore-pact' },
      },
      {
        id: 'well-break-stone',
        label: 'Разбить камень и оборвать договор',
        consequence: 'Колодец осыпается, зато вода больше никому не принадлежит. Село должно искать новый источник.',
        nextSceneId: 'tavern',
        effects: { coins: 4, reputation: 4, experience: 13 },
        addItem: { id: 'black-stone-shard', name: 'Осколок чёрного камня' },
        completeQuest: { id: 'well', outcome: 'break-pact' },
      },
    ],
  },
  'beast-edge': {
    id: 'beast-edge',
    region: 'Пепельная вырубка',
    title: 'След, который не остывает',
    text: 'Следы зверя обжигают иней. Он ходит вокруг трёх дворов, но нападает только на скот с княжеским клеймом. В лесу слышен кашель старого углежога.',
    choices: [
      {
        id: 'beast-track',
        label: 'Прочитать след и подойти против ветра',
        consequence: 'Ты понимаешь: зверь ранен железным капканом и нападает из боли, а не голода.',
        nextSceneId: 'beast-lair',
        effects: { insight: 2 },
        addFlag: 'beast-advantage',
        requires: { profession: 'hunter' },
      },
      {
        id: 'beast-ask',
        label: 'Расспросить углежога',
        consequence: 'Углежог признаётся, что дружинники жгли лес, выгоняя жителей ради новой дороги. Волк появился в ту же ночь.',
        nextSceneId: 'beast-lair',
        effects: { insight: 1 },
        addFlag: 'beast-truth',
      },
      {
        id: 'beast-bait',
        label: 'Оставить сухой паёк как приманку',
        consequence: 'Приманка даёт тебе несколько спокойных мгновений у входа в логово.',
        nextSceneId: 'beast-lair',
        removeItem: 'dry-ration',
        addFlag: 'beast-advantage',
        requires: { item: 'dry-ration' },
      },
    ],
  },
  'beast-lair': {
    id: 'beast-lair',
    region: 'Сгоревший лес',
    title: 'Пепельный волк',
    text: 'Волк стоит среди обгоревших сосен. Из его лапы торчит обломок княжеского капкана. За зверем лежат волчата, слишком слабые, чтобы уйти из мёртвого леса.',
    choices: [
      {
        id: 'beast-berries',
        label: 'Усыпить зверя белыми ягодами и снять капкан',
        consequence: 'Волк сопротивляется сну, но боль отступает раньше ярости.',
        nextSceneId: 'beast-verdict',
        removeItem: 'white-berries',
        addFlag: 'beast-spared',
        requires: { item: 'white-berries' },
      },
      {
        id: 'beast-fight',
        label: 'Вступить в бой',
        consequence: 'Зверь опускает голову. Пепел под его лапами вспыхивает красным.',
        nextSceneId: 'beast-lair',
        encounter: {
          contractId: 'ash-wolf',
          questId: 'beast',
          victorySceneId: 'beast-verdict',
          fleeSceneId: 'tavern',
        },
      },
    ],
  },
  'beast-verdict': {
    id: 'beast-verdict',
    region: 'Сгоревший лес',
    title: 'Кому принадлежит лес',
    text: 'Угроза устранена, но причина осталась. Княжеская артель собирается продолжить вырубку, а жители ждут доказательство смерти зверя.',
    choices: [
      {
        id: 'beast-trophy',
        label: 'Принести клеймёный капкан как доказательство',
        consequence: 'Жители понимают, кто первым начал эту охоту. Заказ оплачен, но княжеские люди запоминают тебя.',
        nextSceneId: 'tavern',
        effects: { coins: 9, reputation: 3, experience: 10 },
        addItem: { id: 'princely-trap', name: 'Княжеский капкан' },
        completeQuest: { id: 'beast', outcome: 'expose-prince' },
      },
      {
        id: 'beast-hide-truth',
        label: 'Сказать, что зверь мёртв, и скрыть логово',
        consequence: 'Волчата получают шанс уйти глубже в лес. Ты получаешь плату за удобную ложь.',
        nextSceneId: 'tavern',
        effects: { coins: 12, reputation: 1, experience: 8 },
        completeQuest: { id: 'beast', outcome: 'protect-lair' },
      },
    ],
  },
  'chapter-end': {
    id: 'chapter-end',
    region: 'Граница Верескова',
    title: 'Первая зола',
    text: 'За спиной остаётся село, которое ты не спас и не погубил окончательно. Ты лишь изменил цену его следующего утра. Впереди лежат княжества, где каждое ремесло становится оружием, а каждая победа создаёт новый долг.',
    choices: [
      {
        id: 'chapter-return',
        label: 'Вернуться в трактир и завершить приготовления',
        consequence: 'Ты откладываешь дальнюю дорогу и возвращаешься к знакомому огню.',
        nextSceneId: 'tavern',
      },
    ],
  },
}

export const storySceneIds = new Set(Object.keys(storyScenes))
